# Generated by Django 3.2.5 on 2021-08-18 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='жанр фильма')),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64, verbose_name='имя режиссера')),
                ('last_name', models.CharField(max_length=64, verbose_name='фамилия режиссера')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название фильма')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='дата выхода')),
                ('description', models.CharField(max_length=1024, verbose_name='описание')),
                ('genre', models.ManyToManyField(to='core.Genre')),
                ('producer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.producer')),
            ],
        ),
    ]
