# Generated by Django 3.2.5 on 2021-08-19 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_movie_release_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Producer',
            new_name='Director',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='producer',
            new_name='director',
        ),
    ]
