# Generated by Django 3.2.5 on 2021-08-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210819_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='biography',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='биография'),
        ),
        migrations.AddField(
            model_name='director',
            name='country',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='страна'),
        ),
        migrations.AddField(
            model_name='director',
            name='date_or_birth',
            field=models.DateField(blank=True, null=True, verbose_name='дата рождения'),
        ),
        migrations.AddField(
            model_name='director',
            name='date_or_death',
            field=models.DateField(blank=True, null=True, verbose_name='дата смерти'),
        ),
    ]
