# Generated by Django 3.2.5 on 2021-08-19 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210819_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='director',
            old_name='date_or_birth',
            new_name='date_of_birth',
        ),
        migrations.RenameField(
            model_name='director',
            old_name='date_or_death',
            new_name='date_of_death',
        ),
    ]
