# Generated by Django 3.2.5 on 2021-08-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210819_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='biography',
            field=models.CharField(blank=True, max_length=4096, null=True, verbose_name='биография'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.CharField(max_length=4096, verbose_name='описание'),
        ),
    ]
