# Generated by Django 3.2.5 on 2021-08-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210819_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64, verbose_name='имя актера')),
                ('last_name', models.CharField(max_length=64, verbose_name='фамилия актера')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='дата рождения')),
                ('date_of_death', models.DateField(blank=True, null=True, verbose_name='дата смерти')),
                ('country', models.CharField(blank=True, max_length=32, null=True, verbose_name='страна')),
                ('biography', models.CharField(blank=True, max_length=4096, null=True, verbose_name='биография')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(to='core.Actor'),
        ),
    ]
