# Generated by Django 3.2.5 on 2021-08-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_movie_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/directors/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/movies/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='director',
            name='biography',
            field=models.TextField(blank=True, max_length=4096, null=True, verbose_name='биография'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(max_length=4096, verbose_name='описание'),
        ),
    ]
