# Generated by Django 3.2.5 on 2021-09-01 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_movie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='image',
            field=models.ImageField(blank=True, upload_to='directors/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, upload_to='movies/', verbose_name='Изображение'),
        ),
    ]
