# Generated by Django 3.2.5 on 2021-09-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210901_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/directors/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/movies/', verbose_name='Изображение'),
        ),
    ]
