# Generated by Django 3.2.5 on 2021-09-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20210901_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='image',
            field=models.ImageField(blank=True, upload_to='directors/', verbose_name='Изображение'),
        ),
    ]
