# Generated by Django 3.2.5 on 2021-08-31 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_movie_description'),
        ('accounts', '0005_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_directors',
            field=models.ManyToManyField(to='core.Director'),
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_movies',
            field=models.ManyToManyField(to='core.Movie'),
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/users/', verbose_name='Изображение'),
        ),
    ]
