# Generated by Django 3.2.5 on 2021-08-31 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210831_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='birth_date',
            new_name='date_of_birth',
        ),
    ]
